name = "gifstrem"
compatibility_date = "2024-10-04"
pages_build_output_dir = "apps/web/dist"

[vars]
SESSION_TTL_SECONDS = "604800"

[[d1_databases]]
binding = "DB"
database_name = "gifstrem-db"
database_id = "81607135-7d3b-4b7a-87f5-e0bd9a97e3cf"

[[r2_buckets]]
binding = "GIF_BUCKET"
bucket_name = "gifstrem-gifs"
